### PR TITLE
bib correction - Bao21

### PR DESCRIPTION
**Pull request by onealbao**
Please check. Thanks so much!

### CODE REVIEW

**Comment by lawrennd** [comment]
Hi Shunxing,

Thanks for the fix, although the bib file is no longer the source for generating the website. each paper has it's own file, if you go to the webpage for the paper (https://proceedings.mlr.press/v156/bao21a.html), you'll see an 'edit' button in the top right, if you click on that, you'll edit the relevant information directly.

To go straight there you can click this link: https://github.com/mlresearch/v156/edit/gh-pages/_posts/2021-09-16-bao21a.md

Neil

**Comment by onealbao** [comment]
Thanks so much, Prof. Lawrence. I've created another pull request: https://github.com/mlresearch/v156/pull/3. Please check, thanks! 

I have a quick question, after merging the edit, will it change the author information in google scholar automatically https://scholar.google.com/scholar?hl=en&as_sdt=0%2C43&q=Random+Multi-Channel+Image+Synthesis+for+Multiplexed+Immunofluorescence+Imaging&btnG= as well?

**Comment by lawrennd** [comment]
Yes, it should do. Google scholar crawls our site for that information, and that all gets automatically updated.

From: onealbao ***@***.***>
Date: Tuesday, 5 October 2021 at 21:24
To: mlresearch/v156 ***@***.***>
Cc: Neil David Lawrence ***@***.***>, Comment ***@***.***>
Subject: Re: [mlresearch/v156] bib correction - Bao21 (#2)

Thanks so much, Prof. Lawrence. I've created another pull request.

I have a quick question, after merging the edit, will it change the author information in google scholar automatically [https://scholar.google.com/scholar?hl=en&as_sdt=0%2C43&q=Random+Multi-Channel+Image+Synthesis+for+Multiplexed+Immunofluorescence+Imaging&btnG=] as well?

**Comment by onealbao** [comment]
Awesome. Thanks so much again!

**Pull request closed without merging**
