### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by foxtrotmike**
Updated Ghamdi et al.

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
Thanks for the update … could you just add comment on the nature of the change for the record? (PDF looks fine)

**Review by foxtrotmike — COMMENTED** [review]
Updated the file received from Alghamdi et al. with name correction.

**Comment by foxtrotmike** [comment]
Updated the PDF with file received from Alghamdi et al. with name correction.

**Comment by lawrennd** [comment]
Thanks!

**Pull request merged**
